### ISSUE TITLE
can't delete cache or uninstall the cookie?

### ISSUE THREAD

**Issue by lonycc** [WittBulter/v2ex-cli#12]
Type:
- [x] Bug
- [ ] Feature
- [ ] Help   

Version: 0.2.6

Description:
run [v2 cache -a], return "total_size: 192k"
run [v2 cache -d], enter "Y", return "cache removed"
run [v2 cache -a] again,  return "total_size: 192k"

run [v2 implide], then run [v2 show], still return "lastet,page: 1"

**Comment by lonycc** [comment]
i found that only when i exit the current terminal, open another one, run [v2 cache], return "no cache", same with the [v2 implide]

**Comment by unix** [comment]
append more information plz, like operating system / nodejs version / terminal.

**Comment by lonycc** [comment]
mac os 10.13
node 9.0
terminal iterm

maybe you mean [v2 implode] instead of [v2 implide] in readme.md
