### ISSUE TITLE
package.json with an empty line in the end

### ISSUE THREAD

**Issue by lonycc** [WittBulter/v2ex-cli#16]
Type:
- [x] Bug
- [ ] Feature
- [ ] Help   

Version: 
0.2.6

Description: 
Unexpected end of JSON input while parsing near '...k/download/webpack-1.', your package.json has empty line in the end

**Comment by unix** [comment]
where did this error happen?

**Comment by lonycc** [comment]
while installing, you can remove the empty line and it works.

**Comment by unix** [comment]
can you try `npm i -g v2ex-cli@0.2.6-beta.1`.
i will release to latest version if this version solve your issue.
