### ISSUE TITLE
bad cookie

### ISSUE THREAD

**Issue by merlin95X** [WittBulter/v2ex-cli#2]
F12 network collectXXXX里面的 Request Header里的cookie复制到  `v2 install` 下面   ，显示 `bad cookie`

**Comment by unix** [comment]
有以下几种可能:
1. 你在网站上本身未登录，或是选取的那个请求不包含鉴权信息
2.`cookie` 太短 (length < 10)，不正确

你可以观察你的 `cookie` 中是否包含 `A2="xxx"` 这样的字符，一般有这样的字符才会被认作是可用的。

**Comment by merlin95X** [comment]
好啦，用了错误的cookie...应该直接用 www.v2ex.com这个请求的cookie
