### ISSUE TITLE
连续回复报错

### ISSUE THREAD

**Issue by POPOEVER** [WittBulter/v2ex-cli#7]
Type:
- [x] Bug
- [ ] Feature
- [ ] Help   

Version: 

Description:
回复后对同一帖子再次回复会报错，需要重新 read 帖子一次才可以再次回复成功

**Comment by unix** [comment]
你好，具体是什么错误，你的 NodeJS 版本是多少，麻烦补充一下

**Comment by unix** [comment]
未能重现，请补充更多的信息

**Comment by POPOEVER** [comment]
node 8.6.0

出错信息很长

`POPO-MBP15:~ popo$ v2 reply
ℹ to: post.404070  [前端月薪天花板大概是多少]

**Comment by unix** [comment]
看到了，报错信息包含 cookie，我先帮你编辑了。
在跟进

**Comment by unix** [comment]
是一个鉴权 ID 没有被及时更新的问题，已修复。
见 #11 。
注意更新最新版本 v0.2.6，如果你用的国内的 npm 源，可能要等几分钟源同步的时间。
