### ISSUE TITLE
v2ex-cli can not find cookie in Windows 10

### ISSUE THREAD

**Issue by hwk603** [WittBulter/v2ex-cli#8]
Type:
- [x] Bug
- [ ] Feature
- [ ] Help   

Version: 

- Node  6.11.5

- Windows 10 Version 1703

Description:

![image](https://user-images.githubusercontent.com/7033138/32094324-f4813f24-bb31-11e7-97a0-344bda43f747.png)

![image](https://user-images.githubusercontent.com/7033138/32094339-058ee078-bb32-11e7-8484-3eae1a0cbdd3.png)

**Comment by unix** [comment]
先检查一下 cookie 中有没有 `A2=` 的字符串，如果没有说明这个 cookie 不正确。
cookie 要求是已登录，目标是 v2ex.com 的链接头信息中的所有 cookie。

如果不是这个问题，麻烦看一下 v2ex-cli 的版本，我弄个 windows 测试下。

**Comment by hwk603** [comment]
cookie 应该没问题吧,我之后又手动获取了一次, save 后还是提示找不到 cookie.

![image](https://user-images.githubusercontent.com/7033138/32102427-d1909132-bb4e-11e7-9fb6-fb54db939e01.png)

![image](https://user-images.githubusercontent.com/7033138/32102481-1bea7266-bb4f-11e7-8d79-895570e010f1.png)

![image](https://user-images.githubusercontent.com/7033138/32102499-32a5b7a4-bb4f-11e7-9a85-32f8dd427187.png)

**Comment by unix** [comment]
这个是你的 `cookie` 错误了，可以尝试一下 #9

**Comment by hwk603** [comment]
OK ,Thanks.
