### ISSUE TITLE
Which cookie do i need to make a copy?

### ISSUE THREAD

**Issue by SunsetWan** [WittBulter/v2ex-cli#9]
Type:
- [  ] Bug
- [  ] Feature
- [✔︎ ] Help   

Version: macOS High Sierra 10.13, node 8.8.1

Description:
![screen shot 2017-10-28 at 15134 pm](https://user-images.githubusercontent.com/16316111/32131751-8f382440-bbe8-11e7-845d-1d0e458ba560.png)
I know little about cookie usage. Is there anyone who can help me?

**Comment by unix** [comment]
1. open browser console 
2. select network
3. click `www.v2ex.com` link, find `Request Header`
4. copy `cookie` item


<img width="725" alt="444" src="https://user-images.githubusercontent.com/11304944/32132220-8e75e0ba-bbf2-11e7-9b38-3292fe6799fc.png">

**Comment by SunsetWan** [comment]
To be precise, what I need to copy is that the content of V2EX_TAB.
But the terminal tells me it's a bad cookie.
![screen shot 2017-10-28 at 23951 pm](https://user-images.githubusercontent.com/16316111/32132008-06dde188-bbee-11e7-9b72-7891bb542d73.png)

**Comment by unix** [comment]
you need to use the cookie from **Request Headers**.
Request Headers Cookie contain `A2=.....`

**Comment by SunsetWan** [comment]
I can't find 'A2' item in 'set-cookie' item.
![screen shot 2017-10-28 at 25520 pm](https://user-images.githubusercontent.com/16316111/32132136-8b4d34b2-bbf0-11e7-8506-5e2d4f815c03.png)

**Comment by unix** [comment]
`Request Header => cookie`  

<img width="482" alt="213" src="https://user-images.githubusercontent.com/11304944/32132164-0d91e026-bbf1-11e7-9bfd-7fccd5c210da.png">

**Comment by SunsetWan** [comment]
That's right! I have found it.
But the photo you first uploaded showed the info of **Response Headers** , not **Request Headers**. It made me confused.
I got the message 'cookie saved', Thanks a lot!

**Comment by unix** [comment]
🤕 🤕 🤕 
thanks, I've updated the picture.
